### ISSUE TITLE
Compiling Failure

### ISSUE THREAD

**Issue by godreborn** [orbisdev/orbisdev#4]
I can't seem to compile orbisdev.  I've tried debian, ubuntu 20.04, and ubuntu 18.04.  they all fail at the same spot.
![1637068449254](https://user-images.githubusercontent.com/13548481/142051385-878d0f2b-4df5-4b13-8074-e1ce1244cbe1.png)

**Comment by fjtrujy** [comment]
There is PR pending to be merged that will solve your problem

**Comment by fjtrujy** [comment]
I think that we can close that issue
